version: '3'
# with shared properties
services:
  node-api-app:
    build: ./API
    ports:
      - '3000:3000'
    env_file:
      - ./API/.env
    environment:
      - MONGO_USER=rootuser
      - MONGO_PASSWORD=rootpass
    depends_on:
      - mongodb

  nginx-web-app:
    build: ./Web
    ports:
      - '8080:80'
    environment:
      - PORT=8080
    command: npm start

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    volumes:
      - mongo-db:/data/db

# all named volumes
volumes:
  mongo-db:


# run app:
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d 
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d 

# to start specific services
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d <container-name>