version: '3'
# with shared properties
services:
  node-api-app:
    build: ./API
    ports:
      - '3000:3000'
    env_file:
      - ./API/.env
  nginx-web-app:
    build: ./Web
    ports:
      - '8080:80'
    environment:
      - PORT=8080
    command: npm start

# run app:
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d 
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d 