version: '3'
services:
  node-api-app:
    build:
      context: ./API
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: node index.js
  nginx-web-app:
    build:
      context: ./Web
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
